name: Build and Push Docker image

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

#      - name: Docker Login
#        run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      
      - name: Run docker build
        run: |
          pwd
          ls ../..
          docker build ../../guestbook --file Dockerfile --tag sebkhedim/guestbook:1.0

      - name: Run docker build
        run: |
          pwd
          ls ../..
          docker build --file guestbook/Dockerfile --tag sebkhedim/guestbook:1.0



